<?php if ($block->hasCmsBlock($block->getCurrentCategory()->getId())): ?>
    <!-- No CMS block present -->
<style>
    .subcategories-block {
        display: flex;
        flex-wrap: nowrap;
        overflow-x: scroll;
        -webkit-overflow-scrolling: touch;
        scroll-behavior: smooth;
        padding: 0px;
        margin: 0;
    }

    .subcategories-block::-webkit-scrollbar {
    display: none;
    }

    .subcategories-block a {
        text-decoration: none;
        color: #333;
        margin: 10px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        display: inline-block;
        width: 200px;
        text-align: center;
        transition: all 0.2s ease-in-out;
    }

    .subcategories-block img {
        display: block;
        margin: 0 auto;
        max-width: 100%;
    }

    .subcategories-block a:hover {
        background-color: #f2f2f2;
        transform: scale(1.05);
    }

    
    @media only screen and (max-width: 500px) {
        .subcategories-block a {
        width: calc(100% - 40px);
    }
    .subcategories-block li {
        min-width: 200px;
    }
    }

    .subcategories-block li {
        list-style: none;
        display: inline-block;
        white-space: nowrap;
    }
</style>

<ul class="subcategories-block">
    <?php foreach ($block->getCategoryCollection() as $subcategory): ?>
        <li>
            <a href="<?php echo $subcategory->getUrl() ?>">
                <img src="<?php echo $subcategory->getImageUrl(); ?>" alt="<?php echo $block->escapeHtml($subcategory->getName()); ?>">
                <?php echo $subcategory->getName() ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>